import { trpc } from "@/lib/trpc";
import { explorerDataState, filterLiveEvents, magnitudeBins, type EventFilters } from "@/lib/eventExplorer";
import { CLOSE_DISTANCE_SAFETY } from "@/lib/closeDistanceSafety";
import { approximateDistanceKm } from "@/lib/geo";
import { isCloseEpicenterDistance, isWithinJapanMapBounds, mapCoordinate, mapDistanceSegment, mapMarkerStyle, mapReferenceRing } from "@/lib/earthquakeMap";
import { JAPAN_REGIONS, type JapanRegion, type SeismicEvent } from "@shared/seismic";
import { AlertTriangle, Ambulance, ArrowLeft, Crosshair, ExternalLink, Flame, Info, LocateFixed, MapPin, Search, ShieldAlert } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";

function localTime(utc: string) {
  return new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Tokyo", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(utc));
}

export default function EventExplorer() {
  const snapshot = trpc.seismic.snapshot.useQuery();
  const [filters, setFilters] = useState<EventFilters>({ period: "7d", minimumMagnitude: 0, region: "All", query: "" });
  const [selected, setSelected] = useState<SeismicEvent | null>(null);
  const [location, setLocation] = useState<{ latitude: number; longitude: number } | null>(null);
  const [locationStatus, setLocationStatus] = useState("Your location is not shown.");
  const dataState = explorerDataState({ isLoading: snapshot.isLoading, isError: snapshot.isError, hasData: Boolean(snapshot.data) });
  const events = useMemo(() => filterLiveEvents(snapshot.data?.events ?? [], filters, new Date()), [snapshot.data?.events, filters]);
  const bins = useMemo(() => magnitudeBins(events), [events]);
  const maxBin = Math.max(...bins.map(bin => bin.count), 1);
  const activeEvent = selected && events.some(event => event.eventId === selected.eventId) ? selected : events[0] ?? null;
  const locationInMap = location ? isWithinJapanMapBounds(location.latitude, location.longitude) : false;
  const selectedDistanceKm = location && activeEvent ? approximateDistanceKm(location, { latitude: activeEvent.latitude, longitude: activeEvent.longitude }) : null;
  const selectedEventIsClose = isCloseEpicenterDistance(selectedDistanceKm);

  useEffect(() => {
    if (selected && !events.some(event => event.eventId === selected.eventId)) setSelected(events[0] ?? null);
  }, [events, selected]);

  const requestLocation = () => {
    if (!("geolocation" in navigator)) {
      setLocation(null);
      setLocationStatus("This browser does not support Current Location.");
      return;
    }
    setLocationStatus("Finding your current location…");
    navigator.geolocation.getCurrentPosition(
      position => {
        const nextLocation = { latitude: position.coords.latitude, longitude: position.coords.longitude };
        setLocation(nextLocation);
        setLocationStatus(isWithinJapanMapBounds(nextLocation.latitude, nextLocation.longitude) ? "Current location is shown on the Japan map for this browser session." : "Your location is outside this Japan-only map view, so no map marker is placed.");
      },
      () => {
        setLocation(null);
        setLocationStatus("Location was not shared. No user marker is shown.");
      },
      { enableHighAccuracy: false, maximumAge: 300_000, timeout: 10_000 },
    );
  };

  if (dataState === "loading") return <ExplorerState title="Live events ကို စစ်ဆေးနေပါသည်…" copy="USGS live dataset ကို ဖတ်နေပါသည်။ အချိန်အနည်းငယ်စောင့်ပါ။" />;
  if (dataState === "error") return <ExplorerState title="Live events ကို ယာယီမဖတ်နိုင်သေးပါ" copy="Data မရရှိချိန်တွင် empty history ကို မပြပါ။ Source connection ကို ပြန်စစ်ရန်အောက်ပါ button ကိုနှိပ်ပါ။" onRetry={() => snapshot.refetch()} />;

  return (
    <main className="min-h-screen bg-[#f5f7f8] text-slate-950">
      <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="inline-flex items-center gap-2 text-sm font-black"><ArrowLeft size={17} />Live monitor</Link><p className="text-xs font-bold text-slate-500">USGS live events only</p></div></header>
      <div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 sm:py-10">
        <section className="rounded-3xl bg-slate-950 p-6 text-white"><p className="text-[10px] font-extrabold tracking-[0.18em] text-slate-400">MAP + HISTORY</p><h1 className="mt-2 text-3xl font-black tracking-tight">Live earthquake map</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">အောက်ပါ marker များသည် USGS live data မှ actual epicenter coordinates ကို ပြထားခြင်းဖြစ်ပါသည်။ Marker အရောင်နှင့်အရွယ်အစားသည် magnitude ကိုပြပြီး၊ map သည် coordinate အခြေပြု approximate Japan view ဖြစ်ပါသည်။</p></section>

        <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-bold">Time range<select value={filters.period} onChange={event => setFilters(current => ({ ...current, period: event.target.value as EventFilters["period"] }))} className="mt-1 block w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm"><option value="24h">Last 24 hours</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option></select></label><label className="text-xs font-bold">Minimum magnitude<select value={filters.minimumMagnitude} onChange={event => setFilters(current => ({ ...current, minimumMagnitude: Number(event.target.value) }))} className="mt-1 block w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm"><option value="0">All magnitudes</option><option value="3">M3+</option><option value="4">M4+</option><option value="5">M5+</option></select></label><label className="text-xs font-bold">Region<select value={filters.region} onChange={event => setFilters(current => ({ ...current, region: event.target.value as JapanRegion | "All" }))} className="mt-1 block w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm"><option value="All">All Japan</option>{JAPAN_REGIONS.map(region => <option key={region} value={region}>{region}</option>)}</select></label><label className="text-xs font-bold">Search place<div className="relative mt-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={15} /><input value={filters.query} onChange={event => setFilters(current => ({ ...current, query: event.target.value }))} className="w-full rounded-xl border border-slate-300 py-2 pl-9 pr-3 text-sm" placeholder="Place or region" /></div></label></div></section>

        <section className="mt-6 grid gap-6 lg:grid-cols-[1.42fr_0.58fr]">
          <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
            <div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-extrabold tracking-[0.18em] text-slate-500">INTERACTIVE MAP</p><h2 className="mt-1 text-xl font-black">{events.length} visible events</h2></div><div className="flex shrink-0 gap-2"><button onClick={requestLocation} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-3 py-2 text-xs font-bold hover:border-slate-950"><Crosshair size={14} />Current Location</button>{location && <button onClick={() => { setLocation(null); setLocationStatus("Current location was cleared from this browser session."); }} className="rounded-xl border border-slate-300 px-3 py-2 text-xs font-bold hover:border-slate-950">Clear</button>}</div></div><p role="status" className="mt-3 text-xs leading-5 text-slate-500">{locationStatus} Precise location is never sent to the server or saved after this session.</p>
            <div className="relative mt-5 aspect-[1.16/1] overflow-hidden rounded-2xl border border-slate-200 bg-[radial-gradient(circle_at_70%_30%,#f9fdff_0%,#dceff8_38%,#c5e0ed_100%)]">
              <div className="absolute inset-0 opacity-40 [background-image:linear-gradient(#85a9bd_1px,transparent_1px),linear-gradient(90deg,#85a9bd_1px,transparent_1px)] [background-size:20%_20%]" />
              <div className="absolute left-[16%] top-[12%] h-[68%] w-[60%] rotate-[22deg] rounded-[45%_55%_50%_38%] border border-white/80 bg-white/20 shadow-[0_10px_30px_rgba(70,120,148,.12)]" aria-hidden="true" />
              <p className="absolute left-4 top-4 text-[10px] font-extrabold tracking-[0.16em] text-slate-600">APPROXIMATE JAPAN COORDINATE MAP</p><p className="absolute right-4 top-4 rounded-full bg-white/75 px-2 py-1 text-[10px] font-bold text-slate-700">USGS coordinates</p>
              <span className="absolute left-[58%] top-[19%] text-[9px] font-extrabold tracking-wider text-slate-500">HOKKAIDO</span><span className="absolute left-[51%] top-[46%] text-[9px] font-extrabold tracking-wider text-slate-500">HONSHU</span><span className="absolute left-[38%] top-[70%] text-[9px] font-extrabold tracking-wider text-slate-500">KYUSHU</span>
              {selectedEventIsClose && activeEvent && (() => { const point = mapCoordinate(activeEvent.latitude, activeEvent.longitude); const ring = mapReferenceRing(activeEvent.latitude); return <span aria-label="Gently pulsing approximate 100 km reference ring around selected epicenter; not an official warning zone" className="map-reference-ring-pulse pointer-events-none absolute z-[4] -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-dashed border-[#b42318] bg-[#b42318]/10" style={{ left: `${point.left}%`, top: `${point.top}%`, width: `${ring.width}%`, height: `${ring.height}%` }} />; })()}
              {locationInMap && location && activeEvent && (() => { const from = mapCoordinate(location.latitude, location.longitude); const to = mapCoordinate(activeEvent.latitude, activeEvent.longitude); const segment = mapDistanceSegment(from, to); return <><div aria-hidden="true" className={`absolute z-[5] h-0 border-t-2 border-dashed ${selectedEventIsClose ? "border-[#b42318]" : "border-slate-900/70"}`} style={{ left: `${segment.left}%`, top: `${segment.top}%`, width: `${segment.length}%`, transform: `rotate(${segment.angle}deg)`, transformOrigin: "0 0" }} /><span className={`absolute z-[15] -translate-x-1/2 -translate-y-1/2 rounded-full px-2 py-1 text-[9px] font-black text-white shadow ${selectedEventIsClose ? "bg-[#b42318]" : "bg-slate-950"}`} style={{ left: `${segment.labelLeft}%`, top: `${segment.labelTop}%` }}>≈ {selectedDistanceKm} km</span></>; })()}
              {events.map(event => { const point = mapCoordinate(event.latitude, event.longitude); const style = mapMarkerStyle(event.magnitude); const selectedMarker = activeEvent?.eventId === event.eventId; return <button key={event.eventId} onClick={() => setSelected(event)} title={`M${event.magnitude.toFixed(1)} · ${event.locality}`} style={{ left: `${point.left}%`, top: `${point.top}%`, width: `${style.size}px`, height: `${style.size}px`, backgroundColor: style.color }} className={`absolute z-10 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white text-[9px] font-black text-white shadow-[0_4px_14px_rgba(18,45,61,.42)] transition hover:scale-110 focus-visible:scale-110 ${selectedMarker ? "ring-4 ring-slate-950/30 scale-110" : ""}`} aria-label={`Select M${event.magnitude.toFixed(1)} event at ${event.locality}`}>M{event.magnitude.toFixed(1)}</button>; })}
              {locationInMap && location && (() => { const point = mapCoordinate(location.latitude, location.longitude); return <span style={{ left: `${point.left}%`, top: `${point.top}%` }} className="absolute z-20 inline-flex -translate-x-1/2 -translate-y-1/2 items-center gap-1 rounded-full border-2 border-slate-950 bg-white px-1.5 py-1 text-[10px] font-black text-slate-950 shadow" aria-label="Your current browser-session location"><LocateFixed size={12} />You</span>; })()}
              {!events.length && <div className="absolute inset-0 z-20 grid place-items-center bg-white/70 p-6 text-center"><p className="rounded-xl bg-white px-4 py-3 text-sm font-bold text-slate-600 shadow-sm">ဒီ filter အတွက် map ပေါ်တွင် live event မတွေ့ရှိပါ။</p></div>}
              <div className="absolute bottom-3 left-3 right-3 z-20 flex flex-wrap gap-2 rounded-xl bg-white/90 px-3 py-2 text-[10px] font-bold text-slate-700 shadow-sm"><span><i className="mr-1 inline-block h-2.5 w-2.5 rounded-full bg-[#2782b5]" />Below M5</span><span><i className="mr-1 inline-block h-2.5 w-2.5 rounded-full bg-[#f79009]" />M5+</span><span><i className="mr-1 inline-block h-2.5 w-2.5 rounded-full bg-[#d92d20]" />M6+</span>{locationInMap && <span><i className="mr-1 inline-block h-2.5 w-2.5 rounded-full border border-slate-950 bg-white" />You</span>}{selectedEventIsClose && <span><i className="mr-1 inline-block h-2.5 w-2.5 rounded-full border-2 border-dashed border-[#b42318]" />100 km reference only</span>}</div>
            </div>
          </article>
          <EventDetail event={activeEvent} distanceKm={selectedDistanceKm} />
        </section>

        <section className="mt-6 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[10px] font-extrabold tracking-[0.18em] text-slate-500">MAGNITUDE DISTRIBUTION</p><h2 className="mt-1 text-xl font-black">Visible event count</h2><div className="mt-5 space-y-3">{bins.map(bin => <div key={bin.label}><div className="mb-1 flex justify-between text-xs font-bold"><span>{bin.label}</span><span>{bin.count}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#7eb7d8]" style={{ width: `${(bin.count / maxBin) * 100}%` }} /></div></div>)}</div></article><article className="rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-5"><p className="text-[10px] font-extrabold tracking-[0.18em] text-slate-500">SEARCHABLE HISTORY</p><h2 className="mt-1 text-xl font-black">USGS live records</h2></div><div className="divide-y divide-slate-100">{events.length ? events.map(event => <button key={event.eventId} onClick={() => setSelected(event)} className={`flex w-full items-center justify-between gap-4 px-5 py-4 text-left hover:bg-slate-50 ${activeEvent?.eventId === event.eventId ? "bg-[#edf7fc]" : ""}`}><span className="min-w-0"><span className="block truncate text-sm font-bold">{event.locality}</span><span className="mt-1 block text-xs text-slate-500">{event.region} · {localTime(event.originTimeUtc)} JST · {event.depthKm === null ? "Depth unknown" : `${event.depthKm.toFixed(0)} km`}</span></span><span className="shrink-0 text-lg font-black">M{event.magnitude.toFixed(1)}</span></button>) : <p className="px-5 py-9 text-center text-sm text-slate-500">ဒီ filter အတွက် live events မတွေ့ရှိပါ။</p>}</div></article></section>
      </div>
    </main>
  );
}

function EventDetail({ event, distanceKm }: { event: SeismicEvent | null; distanceKm: number | null }) {
  const closeDistance = isCloseEpicenterDistance(distanceKm);
  return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[10px] font-extrabold tracking-[0.18em] text-slate-500">SELECTED EVENT</p>{event ? <div className="mt-3"><div className="flex items-start justify-between gap-3"><div><h2 className="text-3xl font-black">M{event.magnitude.toFixed(1)}</h2><p className="mt-1 font-bold">{event.locality}</p></div><span className="rounded-full bg-[#edf7fc] px-2.5 py-1 text-[10px] font-bold text-slate-700">USGS live</span></div>{distanceKm !== null && <div className={`mt-4 rounded-xl border px-3 py-3 ${closeDistance ? "border-[#ef9389] bg-[#fff1ef] text-[#9f1d13]" : "border-[#bdd5c6] bg-[#f2fbf5]"}`}><p className="text-[10px] font-extrabold tracking-[0.14em]">FROM CURRENT LOCATION</p><p className="mt-1 text-lg font-black">Approximately {distanceKm.toLocaleString()} km</p>{closeDistance && <p className="mt-1 text-xs font-black">Within 100 km — check official local information if needed.</p>}<p className={`mt-1 text-xs leading-5 ${closeDistance ? "text-[#9f1d13]" : "text-slate-600"}`}>Epicenter သို့ တန်းဖြောင့်အကွာအဝေးသာဖြစ်ပြီး လမ်းခရီးအကွာအဝေး သို့မဟုတ် official warning area မဟုတ်ပါ။</p></div>}{closeDistance && <CloseDistanceSafety />}<p className="mt-4 rounded-xl bg-slate-50 px-3 py-2 text-xs leading-5 text-slate-600">Map marker သည် USGS က ထုတ်ပေးသော epicenter coordinate ကို approximate map ပေါ်တွင်ထားခြင်းဖြစ်သည်။ တရားဝင် emergency warning area မဟုတ်ပါ။</p><dl className="mt-4 divide-y divide-slate-100 text-sm"><Detail label="Region" value={event.region} /><Detail label="Depth" value={event.depthKm === null ? "Unknown" : `${event.depthKm.toFixed(1)} km`} /><Detail label="Time" value={`${localTime(event.originTimeUtc)} JST`} /><Detail label="Source" value="USGS public CSV" /></dl><a href={event.sourceUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-slate-700 underline underline-offset-4"><MapPin size={14} />Open source record</a></div> : <div className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-600"><Info className="mb-2" size={18} />Marker တစ်ခုကိုနှိပ်ပြီး event details ကိုကြည့်ပါ။ User location သည် optional ဖြစ်ပြီး page ကိုပိတ်လျှင် မသိမ်းထားပါ။</div>}</article>;
}

function CloseDistanceSafety() {
  const [ambulanceFire, police] = CLOSE_DISTANCE_SAFETY.contacts;
  return <section aria-labelledby="close-distance-safety-title" className="mt-4 rounded-2xl border border-[#ef9389] bg-[#fff7f5] p-4 text-slate-900"><div className="flex items-start gap-2"><AlertTriangle className="mt-0.5 shrink-0 text-[#b42318]" size={18} /><div><p className="text-[10px] font-extrabold tracking-[0.14em] text-[#9f1d13]">CLOSE-DISTANCE SAFETY REMINDER</p><h3 id="close-distance-safety-title" className="mt-1 text-base font-black">အရေးပေါ်အတွက် ဆက်သွယ်ရန်နှင့် ဘေးကင်းရေး</h3><p className="mt-1 text-xs leading-5 text-slate-700">Distance 100 km အတွင်းဟု ပြသခြင်းသည် official warning သို့မဟုတ် evacuation order မဟုတ်ပါ။ အရေးပေါ်တကယ်ဖြစ်လျှင်သာ အောက်ပါနံပါတ်များကိုခေါ်ပါ။</p></div></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><a href={ambulanceFire.href} className="flex items-center gap-3 rounded-xl bg-[#b42318] px-3 py-3 text-white shadow-sm hover:bg-[#901f17]"><Ambulance size={18} /><span><span className="block text-lg font-black">{ambulanceFire.number}</span><span className="block text-[10px] font-bold">{ambulanceFire.label}</span></span></a><a href={police.href} className="flex items-center gap-3 rounded-xl border border-[#ef9389] bg-white px-3 py-3 text-[#9f1d13] hover:bg-[#fff1ef]"><ShieldAlert size={18} /><span><span className="block text-lg font-black">{police.number}</span><span className="block text-[10px] font-bold">{police.label}</span></span></a></div><div className="mt-4 space-y-2 rounded-xl bg-white/80 p-3 text-xs leading-5 text-slate-700"><p className="flex gap-2"><ShieldAlert className="mt-0.5 shrink-0 text-[#b42318]" size={15} /><span>Calm နေပြီး သင့်အနီးအနားရှိ အန္တရာယ်များမှ ကိုယ့်ကိုကာကွယ်ကာ staff နှင့် local authority ညွှန်ကြားချက်များကိုလိုက်နာပါ။</span></p><p className="flex gap-2"><Flame className="mt-0.5 shrink-0 text-[#b42318]" size={15} /><span>Building အတွင်းဖြစ်လျှင် လုံခြုံမှသာ အပြင်ထွက်ပါ; မီးအန္တရာယ်ကိုလည်း သတိပြုပါ။</span></p><p className="flex gap-2"><MapPin className="mt-0.5 shrink-0 text-[#b42318]" size={15} /><span>ကမ်းရိုးတန်းတွင် အားပြင်း/ကြာရှည်တုန်ခါမှုရှိလျှင် official tsunami information ကိုစစ်ပြီး higher ground သို့သွားပါ။</span></p></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs font-bold"><a href={CLOSE_DISTANCE_SAFETY.resources.safetyTips} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-[#9f1d13] underline underline-offset-4">Japan Tourism Agency Safety Tips <ExternalLink size={12} /></a><a href={CLOSE_DISTANCE_SAFETY.resources.emergencyContacts} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-[#9f1d13] underline underline-offset-4">Emergency contact source <ExternalLink size={12} /></a></div></section>;
}

function Detail({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3 py-3"><dt className="text-slate-500">{label}</dt><dd className="text-right font-bold">{value}</dd></div>; }

function ExplorerState({ title, copy, onRetry }: { title: string; copy: string; onRetry?: () => void }) {
  return <main className="grid min-h-screen place-items-center bg-[#f5f7f8] px-5 text-center"><div className="max-w-sm rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><Info className="mx-auto text-slate-500" size={24} /><h1 className="mt-4 text-xl font-black">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p>{onRetry && <button onClick={onRetry} className="mt-5 rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">ပြန်စစ်ရန်</button>}<Link href="/" className="mt-4 block text-sm font-bold text-slate-600 underline underline-offset-4">Live monitor သို့ပြန်သွားရန်</Link></div></main>;
}
