import { trpc } from "@/lib/trpc";
import { ArrowLeft, CircleAlert, ClipboardCheck, LockKeyhole, TrendingUp } from "lucide-react";
import { Link } from "wouter";

function localTime(value: string | null) { return value ? new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Tokyo", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value)) : "Unavailable"; }
function percentage(value: number | null) { return value === null ? "—" : `${(value * 100).toFixed(1)}%`; }

export default function Forecasts() {
  const snapshot = trpc.seismic.snapshot.useQuery();
  if (snapshot.isLoading) return <ForecastState title="Model status ကို စစ်ဆေးနေပါသည်…" />;
  if (snapshot.isError || !snapshot.data) return <ForecastState title="Model status ကို ယာယီမဖတ်နိုင်သေးပါ" retry={() => snapshot.refetch()} />;
  const { model, modelHistory, regions, forecastOutcomes } = snapshot.data;
  const production = model.status === "production";
  return <main className="min-h-screen bg-[#f5f7f8] text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="inline-flex items-center gap-2 text-sm font-black"><ArrowLeft size={17} />Live monitor</Link><p className="text-xs font-bold text-slate-500">Forecasts & model history</p></div></header><div className="mx-auto max-w-5xl px-5 py-7 sm:px-8 sm:py-10">
    <section className="rounded-3xl bg-slate-950 p-6 text-white"><p className="text-[10px] font-extrabold tracking-[0.18em] text-slate-400">FORECASTING</p><h1 className="mt-2 text-3xl font-black tracking-tight">Probability, not prediction</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">ဒီစာမျက်နှာသည် exact earthquake prediction မဟုတ်ပါ။ Probability များကို real USGS model တစ်ခု chronological evaluation, calibration နှင့် promotion gates များအားလုံး pass ဖြစ်ပြီးမှသာပြပါမည်။</p></section>
    {!production ? <section className="mt-6 rounded-3xl border border-[#b8d9eb] bg-[#edf7fc] p-6"><div className="flex items-start gap-3"><LockKeyhole className="mt-0.5 shrink-0" size={22} /><div><h2 className="text-xl font-black">Current probability: unavailable</h2><p className="mt-2 text-sm leading-6 text-slate-700">လက်ရှိ USGS model သည် genuine promoted production model မဟုတ်သေးပါ။ 500 validated records, 90-day history, chronological held-out metrics, calibration နှင့် production-comparison safeguards များပြည့်မှသာ probability output ရှိနိုင်ပါသည်။</p></div></div></section> : <section className="mt-6 rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex items-start gap-3"><TrendingUp className="mt-0.5 shrink-0" size={22} /><div><h2 className="text-xl font-black">Current production probabilities</h2><p className="mt-2 text-sm leading-6 text-slate-700">This is a calibrated probabilistic estimate, not an official warning or exact earthquake prediction.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{regions.map(region => <article key={region.region} className="rounded-2xl bg-white p-4"><p className="text-xs font-bold text-slate-500">{region.region}</p><p className="mt-2 text-2xl font-black">{region.probabilityM4_24h === null ? "—" : `${region.probabilityM4_24h.toFixed(1)}%`}</p><p className="mt-1 text-xs text-slate-500">M4+ in next 24h</p></article>)}</div></section>}
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-xl font-black"><ClipboardCheck size={20} />Current model gate</h2><dl className="mt-4 divide-y divide-slate-100 text-sm"><Row label="Status" value={model.status} /><Row label="Version" value={model.version ?? "No promoted USGS version"} /><Row label="Target" value={model.target} /><Row label="Calibration" value={model.calibration} /></dl></article><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-xl font-black"><CircleAlert size={20} />Forecast vs actual</h2>{forecastOutcomes.status === "available" ? <dl className="mt-4 divide-y divide-slate-100 text-sm"><Row label="Closed production windows" value={String(forecastOutcomes.closedCount)} /><Row label="Observed positive windows" value={String(forecastOutcomes.positives)} /><Row label="Mean forecast probability" value={`${(forecastOutcomes.meanProbability! * 100).toFixed(1)}%`} /><Row label="Outcome Brier score" value={String(forecastOutcomes.brierScore)} /><Row label="Latest closed window" value={`${localTime(forecastOutcomes.latestClosedAt)} JST`} /></dl> : <p className="mt-4 text-sm leading-6 text-slate-600">Unavailable: there are no closed production forecast rows to compare against actual outcomes yet. No synthetic backtest or proxy result is shown.</p>}</article></section>
    <section className="mt-6 rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-5"><p className="text-[10px] font-extrabold tracking-[0.18em] text-slate-500">MODEL HISTORY</p><h2 className="mt-1 text-xl font-black">USGS-only chronological reports</h2></div><div className="divide-y divide-slate-100">{modelHistory.length ? modelHistory.map(report => <article key={`${report.modelVersion}-${report.trainedAt}`} className="grid gap-3 px-6 py-5 sm:grid-cols-[1fr_auto]"><div><p className="text-sm font-black">{report.modelVersion}</p><p className="mt-1 text-xs text-slate-500">{report.target} · {report.status} · {localTime(report.trainedAt)} JST</p></div><div className="grid grid-cols-2 gap-x-5 gap-y-1 text-xs"><span>PR-AUC <b>{percentage(report.metrics.prAuc)}</b></span><span>Recall <b>{percentage(report.metrics.recall)}</b></span><span>Brier <b>{report.metrics.brierScore ?? "—"}</b></span><span>ECE <b>{percentage(report.metrics.expectedCalibrationError)}</b></span></div></article>) : <p className="px-6 py-10 text-center text-sm text-slate-500">No USGS chronological model report is available yet. This is expected until the real-data gates are met.</p>}</div></section>
  </div></main>;
}

function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-5 py-3"><dt className="text-slate-500">{label}</dt><dd className="max-w-[62%] text-right font-bold">{value}</dd></div>; }
function ForecastState({ title, retry }: { title: string; retry?: () => void }) { return <main className="grid min-h-screen place-items-center bg-[#f5f7f8] px-5 text-center"><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><CircleAlert className="mx-auto text-slate-500" size={24} /><h1 className="mt-4 text-xl font-black">{title}</h1>{retry && <button onClick={retry} className="mt-5 rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">ပြန်စစ်ရန်</button>}<Link href="/" className="mt-4 block text-sm font-bold text-slate-600 underline underline-offset-4">Live monitor သို့ပြန်သွားရန်</Link></div></main>; }
