import { AlertTriangle, ArrowLeft, ExternalLink, Radio, ShieldCheck, Waves } from "lucide-react";
import { Link } from "wouter";
import { informationBoundary, safetySteps } from "./safetyCopy";

const JMA_TSUNAMI_URL = "https://www.jma.go.jp/bosai/map.html#contents=tsunami&lang=en";
const USGS_SAFETY_URL = "https://www.usgs.gov/faqs/what-should-i-do-during-earthquake";

export default function Safety() {
  return <main className="min-h-screen bg-[#f5f7f8] text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="inline-flex items-center gap-2 text-sm font-black"><ArrowLeft size={17} />Live monitor</Link><p className="text-xs font-bold text-slate-500">Safety guide</p></div></header><div className="mx-auto max-w-5xl px-5 py-7 sm:px-8 sm:py-10">
    <section className="rounded-3xl bg-[#10233c] p-6 text-white sm:p-8"><p className="text-[10px] font-extrabold tracking-[0.18em] text-[#abcde4]">SAFETY</p><h1 className="mt-2 text-3xl font-black tracking-tight">ငလျင်ဖြစ်ချိန် လုံခြုံရေးလမ်းညွှန်</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-200">ဤနေရာသည် အရေးပေါ်အချိန်အတွက် concise guide ဖြစ်ပါသည်။ အန္တရာယ်ရှိပါက သင့်ဒေသမှ တရားဝင်ညွှန်ကြားချက်နှင့် emergency services ကို အမြဲဦးစားပေးပါ။</p><a href="/offline.html" className="mt-5 inline-flex rounded-xl bg-white px-4 py-2 text-sm font-bold text-slate-950">Open offline emergency guide</a></section>
    <section className="mt-6 grid gap-4 md:grid-cols-3">{safetySteps.map((step, index) => <article key={step.title} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><span className="inline-grid h-8 w-8 place-items-center rounded-full bg-[#e5f2fa] text-sm font-black text-slate-700">{index + 1}</span><h2 className="mt-4 text-xl font-black">{step.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{step.body}</p></article>)}</section>
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-3xl border border-[#b8d9eb] bg-[#edf7fc] p-6"><div className="flex items-center gap-2"><Waves size={20} /><h2 className="text-xl font-black">Tsunami information</h2></div><p className="mt-3 text-sm leading-6 text-slate-700">{informationBoundary.tsunami}</p><a href={JMA_TSUNAMI_URL} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-bold underline underline-offset-4">Open official JMA tsunami information <ExternalLink size={14} /></a></article><article className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-center gap-2"><AlertTriangle size={20} /><h2 className="text-xl font-black">Important boundary</h2></div><p className="mt-3 text-sm leading-6 text-slate-700">{informationBoundary.alerts}</p><p className="mt-3 text-sm leading-6 text-slate-700">{informationBoundary.forecast}</p></article></section>
    <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck size={20} /><h2 className="text-xl font-black">Verified information only</h2></div><p className="mt-3 text-sm leading-6 text-slate-600">This app’s live activity comes from the USGS public CSV source. Official tsunami information, evacuation orders, and emergency instructions must come from the relevant authorities. Do not use the dashboard as a substitute for emergency services.</p><div className="mt-4 flex flex-wrap gap-3"><a href={USGS_SAFETY_URL} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-3 py-2 text-sm font-bold hover:border-slate-950"><Radio size={15} />USGS safety guidance <ExternalLink size={14} /></a><a href={JMA_TSUNAMI_URL} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-3 py-2 text-sm font-bold hover:border-slate-950"><Waves size={15} />JMA tsunami page <ExternalLink size={14} /></a></div></section>
  </div></main>;
}
