import { trpc } from "@/lib/trpc";
import { LiveDataErrorState, LiveDataLoadingState } from "@/components/LiveDataLoadingState";
import { ArrowLeft, BellOff, CheckCircle2, CircleAlert, Database, RefreshCcw, ServerCog } from "lucide-react";
import { Link } from "wouter";

function localTime(value: string | null) { return value ? new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Tokyo", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value)) : "Unavailable"; }
function statusLabel(status: string) { return ({ active: "Active", delayed: "Delayed", stale: "Stale", unavailable: "Unavailable" } as Record<string, string>)[status] ?? status; }

export default function SystemHealth() {
  const snapshot = trpc.seismic.snapshot.useQuery();
  if (snapshot.isLoading) return <LiveDataLoadingState title="System status ကို စစ်ဆေးနေပါသည်…" detail="USGS source freshness၊ data-quality checks နှင့် model gate state ကို ဖတ်နေပါသည်။" compact />;
  if (snapshot.isError || !snapshot.data) return <LiveDataErrorState title="System status ကို ယာယီမဖတ်နိုင်သေးပါ" detail="Live source status မရရှိသေးပါ။ အတည်မပြုနိုင်သော health state ကို မပြသပါ။" onRetry={() => void snapshot.refetch()} />;
  const { system, collection, model } = snapshot.data;
  const statusClass = system.source.status === "active" ? "bg-emerald-100 text-emerald-800" : system.source.status === "delayed" ? "bg-amber-100 text-amber-800" : "bg-rose-100 text-rose-800";
  return <main className="min-h-screen bg-[#f5f7f8] text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="inline-flex items-center gap-2 text-sm font-black"><ArrowLeft size={17} />Live monitor</Link><p className="text-xs font-bold text-slate-500">System health</p></div></header><div className="mx-auto max-w-5xl px-5 py-7 sm:px-8 sm:py-10">
    <section className="seismic-hero rounded-3xl p-6 text-white"><div className="seismic-hero-grid" aria-hidden="true" /><p className="relative text-[10px] font-extrabold tracking-[0.18em] text-sky-200">SYSTEM STATUS</p><h1 className="relative mt-2 text-3xl font-black tracking-tight">Data နှင့် system အခြေအနေ</h1><p className="relative mt-2 text-sm leading-6 text-slate-200">ဒီစာမျက်နှာသည် source freshness, data checks, alert health နှင့် model availability ကို ရိုးသားစွာပြပါသည်။</p></section>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card icon={<ServerCog size={19} />} title="USGS source" value={statusLabel(system.source.status)} note={system.source.freshnessMinutes === null ? "No verified collection time" : `${system.source.freshnessMinutes} min since collection`} tone={statusClass} /><Card icon={<Database size={19} />} title="Validated live events" value={String(system.source.acceptedEvents)} note={`Last collection: ${localTime(system.source.lastCollection)} JST`} /><Card icon={<CheckCircle2 size={19} />} title="Alert history" value={String(system.alerts.historyCount)} note={system.alerts.latestDetectedAt ? `Latest: ${localTime(system.alerts.latestDetectedAt)} JST` : "No alert record yet"} /><Card icon={<BellOff size={19} />} title="Background notification" value="Not configured" note="In-app history continues; browser permission is optional." /></section>
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-xl font-black"><Database size={20} />Data-quality check</h2><dl className="mt-4 divide-y divide-slate-100 text-sm"><Row label="Invalid rows rejected (last run)" value={system.quality.invalidRejected === null ? "Unavailable" : String(system.quality.invalidRejected)} /><Row label="Outside Japan envelope (last run)" value={system.quality.outsideEnvelope === null ? "Unavailable" : String(system.quality.outsideEnvelope)} /><Row label="New events evaluated for alerts" value={system.quality.newEventsConsidered === null ? "Unavailable" : String(system.quality.newEventsConsidered)} /><Row label="Schedule" value={collection.nextRun} /></dl></article><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-xl font-black"><CircleAlert size={20} />Model status</h2><p className="mt-4 text-2xl font-black">{model.status === "production" ? "Production model available" : "Prediction unavailable"}</p><p className="mt-3 text-sm leading-6 text-slate-600">{model.calibration}</p><dl className="mt-4 divide-y divide-slate-100 text-sm"><Row label="Model version" value={model.version ?? "No promoted USGS model"} /><Row label="Target" value={model.target} /><Row label="Alert delivery" value="In-app detection history only" /></dl></article></section>
    <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm leading-6 text-slate-600">Source: <a href={collection.sourceUrl} target="_blank" rel="noreferrer" className="font-bold underline underline-offset-4">USGS public downloadable CSV</a>. JMA historical records remain excluded from the live dashboard, alert engine, and USGS production model. “Stale” and “Unavailable” are system states, not claims that no earthquake occurred.</p></section>
  </div></main>;
}

function Card({ icon, title, value, note, tone }: { icon: React.ReactNode; title: string; value: string; note: string; tone?: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-slate-500">{icon}<p className="text-xs font-bold">{title}</p></div><p className={`mt-3 inline-flex rounded-full px-2.5 py-1 text-sm font-black ${tone ?? "text-slate-950"}`}>{value}</p><p className="mt-3 text-xs leading-5 text-slate-500">{note}</p></article>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-5 py-3"><dt className="text-slate-500">{label}</dt><dd className="max-w-[58%] text-right font-bold">{value}</dd></div>; }
function HealthState({ title, retry }: { title: string; retry?: () => void }) { return <main className="grid min-h-screen place-items-center bg-[#f5f7f8] px-5 text-center"><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><CircleAlert className="mx-auto text-slate-500" size={24} /><h1 className="mt-4 text-xl font-black">{title}</h1>{retry && <button onClick={retry} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white"><RefreshCcw size={15} />ပြန်စစ်ရန်</button>}<Link href="/" className="mt-4 block text-sm font-bold text-slate-600 underline underline-offset-4">Live monitor သို့ပြန်သွားရန်</Link></div></main>; }
